### ISSUE TITLE
use with React native (no fs.createReadStream function available)

### ISSUE THREAD

**Issue by faceyspacey** [grayleonard/node-youtube-resumable-upload#11]
Hey there I'd like to use this with React Native, but they don't support the `createReadSream` function yet:

https://github.com/johanneslumpe/react-native-fs
https://github.com/johanneslumpe/react-native-fs/issues/23

I do have access to the device file system and can make requests to outside servers just like Node can (rather than the browser). What would be an alternative approach to piping from one to the other? When I get this working, I'll submit a PR so you have a React Native offering as well.

**Comment by grayleonard** [comment]
You may want to look at the official [googleapi](https://github.com/google/google-api-nodejs-client) repo -- it doesn't use `createReadStream`, but rather `readFileSync`for file uploading.

**Comment by AppleMango23** [comment]
so react-native doesnt support fs.createReadStream?
